//! The record written for every asset.
//!
//! Two shapes come out of the same data and must never be produced separately. One file per
//! asset, `{blake3}.json`, published to R2 so the metadata API can answer a single lookup
//! without reading anything else. One merged file, committed, so the site build can inline
//! placeholders into articles without the images being present at all.
//!
//! Both are generated by one command in one pass. Nothing here is ever hand-edited: the
//! originals live outside git, so a manually corrected manifest would be a claim nothing can
//! check.

use super::encode::Format;
use super::{Derived, Variant};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Bumped when the shape changes, so a reader can tell rather than guess. The first change
/// without one is the one that corrupts silently.
///
/// 1. The original shape.
/// 2. Assets carry a `description`, so alt text travels with the image rather than with each
///    article that happens to reference it.
pub const VERSION: u32 = 2;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Document {
	pub version: u32,
	pub media: Media,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Media {
	#[serde(rename = "type")]
	pub kind: String,
	/// ISO 8601 in UTC. Not local time: a record that means a different instant depending on
	/// where it is read is not a record.
	pub created: String,
	pub updated: String,
	/// The original's content id, and the identity of the asset.
	pub blake3: String,
	/// Base64 thumbhash: the compact canonical placeholder.
	pub thumbhash: String,
	/// The same placeholder decoded and re-encoded tiny, ready to inline. Carried alongside
	/// the hash so an article needs no decoder script to paint it.
	pub preview: String,
	pub source: Source,
	/// What this image shows, written for someone who cannot see it.
	///
	/// Held with the asset rather than with a reference, because it describes the picture and
	/// not the place it appears. An article that wants different wording for its own context
	/// overrides it; every other reference gets this for free, including the ones written
	/// years later. Filled by `cms alt`.
	#[serde(default, skip_serializing_if = "Option::is_none")]
	pub description: Option<String>,
	/// Whether this asset carries a variant at the original's own resolution.
	///
	/// Recorded rather than inferred so re-deriving reproduces what was published. Comparing
	/// the top variant against the source would guess wrong for every image that happens to
	/// sit below the cap, where the two are the same size for an unrelated reason.
	#[serde(default)]
	pub original: bool,
	/// Keyed by each variant's own content id, exactly as the asset is keyed by the
	/// original's. Every stored object is addressed the same way.
	pub variants: BTreeMap<String, VariantRecord>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Source {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	/// Reduced by the greatest common divisor, so it is exact rather than snapped to a
	/// familiar name. Screenshots rarely land on a recognisable ratio.
	pub ratio: String,
	pub bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VariantRecord {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	/// Normalised 0..1, as a number so it can be compared without parsing.
	pub quality: f32,
	pub bytes: u64,
}

/// Every asset, merged. This is the file that gets committed.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Merged {
	pub version: u32,
	pub generated: String,
	pub assets: BTreeMap<String, Media>,
}

/// Bring a manifest read from disk up to the current shape, in place.
///
/// Returns whether anything moved, so a caller knows to republish the per-asset records that
/// were written under the old shape. One-way and one-time: the upgraded file is written back,
/// so there is never a v1 reader to keep working. Two readers for two shapes is how a format
/// stops having a current version at all.
///
/// A field added with `#[serde(default)]` is already correct by the time this runs -- the
/// version number is the part that has to be said out loud, because the next migration needs
/// to know where it is starting from.
pub fn migrate(merged: &mut Merged) -> bool {
	if merged.version >= VERSION {
		return false;
	}
	merged.version = VERSION;
	true
}

pub fn ratio_of(width: u32, height: u32) -> String {
	let divisor = gcd(width, height).max(1);
	format!("{}:{}", width / divisor, height / divisor)
}

fn gcd(a: u32, b: u32) -> u32 {
	if b == 0 { a } else { gcd(b, a % b) }
}

pub fn now() -> String {
	jiff::Timestamp::now().to_string()
}

fn record(variant: &Variant) -> VariantRecord {
	VariantRecord {
		mime: variant.format.mime().to_owned(),
		width: variant.width,
		height: variant.height,
		quality: variant.format.quality(),
		bytes: variant.bytes.len() as u64,
	}
}

/// Build the record for one asset. `created` is carried over when the asset was seen before,
/// so re-running does not rewrite the day it first appeared.
pub fn media_for(
	derived: &Derived,
	source_mime: &str,
	source_bytes: u64,
	created: Option<&str>,
	keep_original: bool,
) -> Media {
	let timestamp = now();
	Media {
		kind: "image".to_owned(),
		created: created.unwrap_or(&timestamp).to_owned(),
		updated: timestamp,
		blake3: derived.cid.clone(),
		thumbhash: STANDARD.encode(&derived.thumb),
		preview: format!(
			"data:{};base64,{}",
			Format::Webp.mime(),
			STANDARD.encode(&derived.preview)
		),
		description: None,
		source: Source {
			mime: source_mime.to_owned(),
			width: derived.width,
			height: derived.height,
			ratio: ratio_of(derived.width, derived.height),
			bytes: source_bytes,
		},
		original: keep_original,
		variants: derived
			.variants
			.iter()
			.map(|variant| (variant.cid.clone(), record(variant)))
			.collect(),
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn reduces_a_ratio_exactly() {
		assert_eq!(ratio_of(1920, 1080), "16:9");
		assert_eq!(ratio_of(800, 600), "4:3");
		assert_eq!(ratio_of(500, 500), "1:1");
	}

	#[test]
	fn does_not_pretend_an_awkward_ratio_is_a_familiar_one() {
		// A screenshot is whatever the window was. Snapping this to 16:9 would be a lie that
		// an aspect-ratio box would then render wrong.
		assert_eq!(ratio_of(2356, 1204), "589:301");
	}

	#[test]
	fn survives_a_zero_dimension() {
		assert_eq!(ratio_of(0, 0), "0:0");
	}

	#[test]
	fn timestamps_are_iso_8601_in_utc() {
		let value = now();
		assert!(value.ends_with('Z'), "not UTC: {value}");
		assert!(value.contains('T'), "not ISO 8601: {value}");
	}

	#[test]
	fn a_document_round_trips_through_json() {
		let document = Document {
			version: VERSION,
			media: Media {
				kind: "image".into(),
				created: "2026-07-30T13:14:52Z".into(),
				updated: "2026-07-30T13:14:52Z".into(),
				blake3: "44b6081deaf0242ca3bf83d62a3b6c95".into(),
				thumbhash: "1QcSHQRnh493".into(),
				preview: "data:image/webp;base64,UklGRh4".into(),
				description: None,
				source: Source {
					mime: "image/png".into(),
					width: 2356,
					height: 1204,
					ratio: ratio_of(2356, 1204),
					bytes: 6_612_480,
				},
				original: false,
				variants: BTreeMap::new(),
			},
		};
		let text = serde_json::to_string(&document).expect("serialise");
		assert_eq!(
			serde_json::from_str::<Document>(&text).expect("deserialise"),
			document
		);
		// `type` is a keyword in Rust and a field name in the document; the rename has to
		// survive both directions.
		assert!(text.contains("\"type\":\"image\""));
	}
}
