declare module 'virtual:articles' {
	import type { Article } from '$lib/content/types';

	/** All nine compiled views of every article, generated by Vite and embedded in the Worker. */
	export const articles: Article[];
}
