declare module 'virtual:articles' {
	import type { Article, Page } from '$lib/content/types';

	/** All nine compiled views of every article, generated by Vite and embedded in the Worker. */
	export const articles: Article[];
	/** All nine compiled views of every standalone page, generated by Vite. */
	export const pages: Page[];
}
