declare module 'virtual:articles' {
	import type { Article, Page } from '$lib/content/types';
	import type { ContentSnapshot } from '$lib/content/snapshot';

	/** The current atomic article and page view, generated by Vite and embedded in the Worker. */
	export let content: ContentSnapshot;
	/** Replace the development snapshot without creating another virtual ESM generation. */
	export function replaceContent(articles: Article[], pages: Page[]): void;
}
