// Generated by scripts/slugs.ts. Run `pnpm run slugs` after adding an article.
//
// Committed so the workspace tasks type check without a build step; slugs.test.ts fails if
// this no longer matches contents/.

export const ARTICLE_SLUGS: ReadonlySet<string> = new Set([
	'architecture/compile-time-rendering',
	'architecture/observation-to-lowering',
	'development/rust-cargo-cranelift-tuning',
	'milestone/less-is-more',
	'mirror/friends-come-in-phases',
	'mirror/less-than-an-hour',
]);
