// Regenerates src/slugs.ts from the content tree.
//
// Which articles exist is a build-time fact -- the API is built from the same repository the
// markdown lives in -- so the read counter validates against a list compiled into the bundle
// rather than letting the database decide what a slug is. A Worker cannot read the tree at
// runtime, which is why this is emitted as a module instead of loaded.
//
// The result is committed: the workspace type check, lint and test tasks run from the root
// and never pass through this package's build. Drift is caught by slugs.test.ts, which runs
// the same walk and compares.

import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CONTENTS = fileURLToPath(new URL('../../../contents', import.meta.url).href);
const OUTPUT = fileURLToPath(new URL('../src/slugs.ts', import.meta.url).href);

/**
 * Every article slug, as the site addresses them.
 *
 * One level of category directory holding markdown files, which is the same shape and the
 * same `category/name` result the site's own build produces. Top-level markdown is a
 * standalone page rather than an article and is deliberately not included.
 */
export async function articleSlugs(contents: string = CONTENTS): Promise<string[]> {
	const slugs: string[] = [];
	for (const category of await readdir(contents, { withFileTypes: true })) {
		if (!category.isDirectory()) continue;
		// oxlint-disable-next-line no-await-in-loop -- a handful of directories, read in order
		for (const entry of await readdir(join(contents, category.name), { withFileTypes: true })) {
			if (entry.isFile() && entry.name.endsWith('.md')) {
				slugs.push(`${category.name}/${entry.name.slice(0, -'.md'.length)}`);
			}
		}
	}
	return slugs.toSorted();
}

export function slugsModule(slugs: readonly string[]): string {
	const entries = slugs.map((slug) => `\t'${slug}',\n`).join('');
	return `// Generated by scripts/slugs.ts. Run \`pnpm run slugs\` after adding an article.
//
// Committed so the workspace tasks type check without a build step; slugs.test.ts fails if
// this no longer matches contents/.

export const ARTICLE_SLUGS: ReadonlySet<string> = new Set([\n${entries}]);
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	await writeFile(OUTPUT, slugsModule(await articleSlugs()), 'utf8');
}
